### PR TITLE
fix embxx_add_cpp11_support when crosscompiling

### PR DESCRIPTION
**Pull request by ajneu**
Hi,

currently the project [embxx_on_rpi](https://github.com/arobenko/embxx_on_rpi/tree/develop) will **fail** when using *develop* branch. Try it!

The reason, is [embxx/cmake/CompilerOptionsFuncs.cmake](https://github.com/arobenko/embxx/blob/ed6ee7697ddc86a4aa368e7311c4a28cfc45d4c3/cmake/CompilerOptionsFuncs.cmake#L77) (on branch _develop_), where 
`set (CMAKE_CXX_STANDARD 11)`  **is not taken(!!!)**, in the special case when the cross-compiler if _forced_ with     
```cmake
cmake_force_c_compiler(  "${CROSS_COMPILE}gcc" GNU)
cmake_force_cxx_compiler("${CROSS_COMPILE}g++" GNU)
```
which occurs in the project [embxx_on_rpi](https://github.com/arobenko/embxx_on_rpi/blob/8f54bda1d85461eb68c8f7786a061263889dc8da/CMakeLists.txt#L13).

This is a problem that's described in the cmake bugtracker [here](https://cmake.org/Bug/view.php?id=15797).

The **solution** is to still use the old-style 
`embxx_add_cxx_flags("--std=c++0x")`, in cases where we are cross-compiling:
**Fixed in this pull-request** -> Here cross-compilation can be nicely detected with the condition `(DEFINED CMAKE_CROSSCOMPILING)`, where `CMAKE_CROSSCOMPILING` will be automatically set when `CMAKE_SYSTEM_NAME` is set ([ref](http://www.vtk.org/Wiki/CMake_Cross_Compiling#Setting_up_the_system_and_toolchain)), which is the case in [embxx_on_rpi](https://github.com/arobenko/embxx_on_rpi/blob/8f54bda1d85461eb68c8f7786a061263889dc8da/CMakeLists.txt#L7).

(For CMake Version 3.6 and newer, `set (CMAKE_CXX_STANDARD 11)` will work, since one does not need to force the compiler, but can then use: `set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)`)

.
.

The other change in the commit is: `test_std_streambuf_access` does not depend on boost.

### CODE REVIEW

**Comment by arobenko** [comment]
I've modified the logic of using the old way of setting flags. Please review.

**Comment by ajneu** [comment]
> Please review.

OK -- reviewed [here](https://github.com/arobenko/embxx/commit/80a80af7c989ae6f0deb780cda1ae05e933a8abd#commitcomment-18017506)

**Comment by arobenko** [comment]
I fixed, the reported problem. Albert, can you please test it in your environment. I'm still using Ubuntu 14.04 as my primary development environment with cmake 2.8.12 and gcc 4.8, haven't had a chance to migrate to Ubuntu 16.04 yet.

**Comment by ajneu** [comment]
It's working nicely.
I'm using Debian Stretch (aka Debian Testing... which is the testing release of debian), setup as shown here: https://github.com/ajneu/gnu_linux_cpp

The develop branches are working nicely! All good. Debian Stretch's cmake is 3.5.2 ([ref](https://packages.debian.org/stretch/cmake)). I also tested with the latest cmake 3.6+ (compiled from source as show at the bottom of [this comment](https://github.com/arobenko/embxx_on_rpi/pull/6#issuecomment-188947904)) and that also works.

> haven't had a chance to migrate to Ubuntu 16.04 yet.

You could also set up a docker container. Or use a schroot. (If I find some time, I will look at these methods more closely myself, as they allow one to easily switch between distros and releases)

**Pull request merged**
